# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lruettgers/dphpc/dphpc-gemm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lruettgers/dphpc/dphpc-gemm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lruettgers/dphpc/dphpc-gemm/CMakeFiles /home/lruettgers/dphpc/dphpc-gemm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lruettgers/dphpc/dphpc-gemm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gemm_core

# Build rule for target.
gemm_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_core
.PHONY : gemm_core

# fast build rule for target.
gemm_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/build
.PHONY : gemm_core/fast

#=============================================================================
# Target rules for targets named gemm_backend_cute

# Build rule for target.
gemm_backend_cute: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_backend_cute
.PHONY : gemm_backend_cute

# fast build rule for target.
gemm_backend_cute/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_backend_cute.dir/build.make CMakeFiles/gemm_backend_cute.dir/build
.PHONY : gemm_backend_cute/fast

#=============================================================================
# Target rules for targets named gemm

# Build rule for target.
gemm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm
.PHONY : gemm

# fast build rule for target.
gemm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm.dir/build.make CMakeFiles/gemm.dir/build
.PHONY : gemm/fast

src/backend/cute/backend_adaptor.o: src/backend/cute/backend_adaptor.cpp.o
.PHONY : src/backend/cute/backend_adaptor.o

# target to build an object file
src/backend/cute/backend_adaptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_backend_cute.dir/build.make CMakeFiles/gemm_backend_cute.dir/src/backend/cute/backend_adaptor.cpp.o
.PHONY : src/backend/cute/backend_adaptor.cpp.o

src/backend/cute/backend_adaptor.i: src/backend/cute/backend_adaptor.cpp.i
.PHONY : src/backend/cute/backend_adaptor.i

# target to preprocess a source file
src/backend/cute/backend_adaptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_backend_cute.dir/build.make CMakeFiles/gemm_backend_cute.dir/src/backend/cute/backend_adaptor.cpp.i
.PHONY : src/backend/cute/backend_adaptor.cpp.i

src/backend/cute/backend_adaptor.s: src/backend/cute/backend_adaptor.cpp.s
.PHONY : src/backend/cute/backend_adaptor.s

# target to generate assembly for a file
src/backend/cute/backend_adaptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_backend_cute.dir/build.make CMakeFiles/gemm_backend_cute.dir/src/backend/cute/backend_adaptor.cpp.s
.PHONY : src/backend/cute/backend_adaptor.cpp.s

src/backend/cute/gemm.o: src/backend/cute/gemm.cu.o
.PHONY : src/backend/cute/gemm.o

# target to build an object file
src/backend/cute/gemm.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_backend_cute.dir/build.make CMakeFiles/gemm_backend_cute.dir/src/backend/cute/gemm.cu.o
.PHONY : src/backend/cute/gemm.cu.o

src/backend/cute/gemm.i: src/backend/cute/gemm.cu.i
.PHONY : src/backend/cute/gemm.i

# target to preprocess a source file
src/backend/cute/gemm.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_backend_cute.dir/build.make CMakeFiles/gemm_backend_cute.dir/src/backend/cute/gemm.cu.i
.PHONY : src/backend/cute/gemm.cu.i

src/backend/cute/gemm.s: src/backend/cute/gemm.cu.s
.PHONY : src/backend/cute/gemm.s

# target to generate assembly for a file
src/backend/cute/gemm.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_backend_cute.dir/build.make CMakeFiles/gemm_backend_cute.dir/src/backend/cute/gemm.cu.s
.PHONY : src/backend/cute/gemm.cu.s

src/core/device_query.o: src/core/device_query.cpp.o
.PHONY : src/core/device_query.o

# target to build an object file
src/core/device_query.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/core/device_query.cpp.o
.PHONY : src/core/device_query.cpp.o

src/core/device_query.i: src/core/device_query.cpp.i
.PHONY : src/core/device_query.i

# target to preprocess a source file
src/core/device_query.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/core/device_query.cpp.i
.PHONY : src/core/device_query.cpp.i

src/core/device_query.s: src/core/device_query.cpp.s
.PHONY : src/core/device_query.s

# target to generate assembly for a file
src/core/device_query.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/core/device_query.cpp.s
.PHONY : src/core/device_query.cpp.s

src/core/dispatcher.o: src/core/dispatcher.cpp.o
.PHONY : src/core/dispatcher.o

# target to build an object file
src/core/dispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/core/dispatcher.cpp.o
.PHONY : src/core/dispatcher.cpp.o

src/core/dispatcher.i: src/core/dispatcher.cpp.i
.PHONY : src/core/dispatcher.i

# target to preprocess a source file
src/core/dispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/core/dispatcher.cpp.i
.PHONY : src/core/dispatcher.cpp.i

src/core/dispatcher.s: src/core/dispatcher.cpp.s
.PHONY : src/core/dispatcher.s

# target to generate assembly for a file
src/core/dispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/core/dispatcher.cpp.s
.PHONY : src/core/dispatcher.cpp.s

src/core/problem.o: src/core/problem.cpp.o
.PHONY : src/core/problem.o

# target to build an object file
src/core/problem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm.dir/build.make CMakeFiles/gemm.dir/src/core/problem.cpp.o
.PHONY : src/core/problem.cpp.o

src/core/problem.i: src/core/problem.cpp.i
.PHONY : src/core/problem.i

# target to preprocess a source file
src/core/problem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm.dir/build.make CMakeFiles/gemm.dir/src/core/problem.cpp.i
.PHONY : src/core/problem.cpp.i

src/core/problem.s: src/core/problem.cpp.s
.PHONY : src/core/problem.s

# target to generate assembly for a file
src/core/problem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm.dir/build.make CMakeFiles/gemm.dir/src/core/problem.cpp.s
.PHONY : src/core/problem.cpp.s

src/utils/data.o: src/utils/data.cpp.o
.PHONY : src/utils/data.o

# target to build an object file
src/utils/data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/utils/data.cpp.o
.PHONY : src/utils/data.cpp.o

src/utils/data.i: src/utils/data.cpp.i
.PHONY : src/utils/data.i

# target to preprocess a source file
src/utils/data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/utils/data.cpp.i
.PHONY : src/utils/data.cpp.i

src/utils/data.s: src/utils/data.cpp.s
.PHONY : src/utils/data.s

# target to generate assembly for a file
src/utils/data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_core.dir/build.make CMakeFiles/gemm_core.dir/src/utils/data.cpp.s
.PHONY : src/utils/data.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gemm"
	@echo "... gemm_backend_cute"
	@echo "... gemm_core"
	@echo "... src/backend/cute/backend_adaptor.o"
	@echo "... src/backend/cute/backend_adaptor.i"
	@echo "... src/backend/cute/backend_adaptor.s"
	@echo "... src/backend/cute/gemm.o"
	@echo "... src/backend/cute/gemm.i"
	@echo "... src/backend/cute/gemm.s"
	@echo "... src/core/device_query.o"
	@echo "... src/core/device_query.i"
	@echo "... src/core/device_query.s"
	@echo "... src/core/dispatcher.o"
	@echo "... src/core/dispatcher.i"
	@echo "... src/core/dispatcher.s"
	@echo "... src/core/problem.o"
	@echo "... src/core/problem.i"
	@echo "... src/core/problem.s"
	@echo "... src/utils/data.o"
	@echo "... src/utils/data.i"
	@echo "... src/utils/data.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

